package estructuraDatos;

public enum TipoMedicamento {
	ANALGESICOS,LAXANTES, ANTINFECCIOSOS, ANTIDEPRESIVOS,
	ANTITUSIVOS, MUCOLITICOS, ANTIACIDOS, ANTIULCEROSOS, 
	ANTIALERGICOS, ANTIFIARREICOS

}
